### ISSUE TITLE
Error: default level:all must be included in custom levels - PDS Refuses to start

### ISSUE THREAD

**Issue by cyrneko** [bluesky-social/pds#108]
hi there!

I've been running my PDS at `bsky.cyrneko.eu` (down at the time of writing) for a bit now and it's been working fine running on a Google-provided VPS, though upon copying the same config over to my homeserver (as the VPS was intended only for testing) and running the docker image(s), the `pds` container always exits with the following error:

```
/app/node_modules/.pnpm/pino@8.21.0/node_modules/pino/lib/levels.js:194
    throw Error(`default level:${defaultLevel} must be included in custom levels`)
    ^

Error: default level:all must be included in custom levels
    at assertDefaultLevelFound (/app/node_modules/.pnpm/pino@8.21.0/node_modules/pino/lib/levels.js:194:11)
    at pino (/app/node_modules/.pnpm/pino@8.21.0/node_modules/pino/pino.js:161:3)
    at Object.<anonymous> (/app/node_modules/.pnpm/@atproto+common@0.4.2/node_modules/@atproto/common/src/logger.ts:21:9)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/app/node_modules/.pnpm/@atproto+common@0.4.2/node_modules/@atproto/common/src/index.ts:8:1)

Node.js v20.11.1

```

As far as I understand these files should be included in the docker image, and because I'm not self-building I don't think the error is on my end either. 

After this error, the PDS exits with error code 0 and it tries again.

Any pointers? I'm no good with typescript and this is an error coming from a dependency, so I can't really read into the code and figure out what is going wrong :/

**Comment by devinivy** [comment]
I assume you're setting the PDS's log level using the `LOG_LEVEL` env var, does that sound that right?  The PDS doesn't support the value "all", but it does support `LOG_LEVEL=debug` for verbose logging.

**Comment by cyrneko** [comment]
Yeah I was, I initially did so and then got pointed to the correct values, but those simply gave...nothing, the PDS simply exits inside the container as if I had the log level unset.
