### ISSUE TITLE
Invite code not accepted

### ISSUE THREAD

**Issue by darnfish** [bluesky-social/pds#29]
Here are the logs from the server, looks like it's using an older version of `@atproto/pds`

```
{"level":50,"time":1705423676962,"pid":7,"hostname":"553e991e2727","name":"xrpc-server","err":{"type":"InvalidRequestError","message":"Provided invite code not available","stack":"Error: Provided invite code not available\n    at ensureCodeIsAvailable (/app/node_modules/@atproto/pds/src/api/com/atproto/server/createAccount.ts:161:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at handler (/app/node_modules/@atproto/pds/src/api/com/atproto/server/createAccount.ts:39:9)\n    at <anonymous> (/app/node_modules/@atproto/xrpc-server/src/server.ts:254:35)","errorMessage":"Provided invite code not available","customErrorName":"InvalidInviteCode"},"msg":"error in xrpc method com.atproto.server.createAccount"}
{"level":30,"time":1705423677647,"pid":7,"hostname":"553e991e2727","name":"pds","req":{"id":28,"method":"POST","url":"/xrpc/com.atproto.server.createAccount","query":{},"params":{},"headers":{"x-real-ip":"","x-forwarded-for":"","host":"bluesky-pds:3000","connection":"close","content-length":"181","sec-ch-ua":"\"Not_A Brand\";v=\"8\", \"Chromium\";v=\"120\"","sec-ch-ua-platform":"\"macOS\"","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","content-type":"application/json","accept":"*/*","origin":"https://bsky.app","sec-fetch-site":"cross-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://bsky.app/","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9"}},"res":{"statusCode":400,"headers":{"x-powered-by":"Express","access-control-allow-origin":"*","content-type":"application/json; charset=utf-8","content-length":"76","etag":"W/\"4c-nTgSJZL7uNTt2++MFFo/NFWNNSU\"","vary":"Accept-Encoding"}},"responseTime":690,"msg":"request completed"}
```

**Comment by Jacob2161** [comment]
A new update is coming with support for the production network and a `pdsadmin` helper CLI, please let us know if there are any issues after this has been pushed. Thank you!
